-- OmniBox Learning Center writable user database
-- Draft migration: 0001
-- Target baseline: SQLite >= 3.38 with JSON functions enabled.
-- All IDs are generated by the application. All timestamps are UTC ISO-8601 text.

PRAGMA foreign_keys = ON;

BEGIN IMMEDIATE;

CREATE TABLE schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    checksum TEXT NOT NULL,
    applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    app_version TEXT NOT NULL
);

CREATE TABLE database_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE learner_profiles (
    id TEXT PRIMARY KEY,
    display_name TEXT,
    timezone TEXT NOT NULL,
    daily_minutes INTEGER NOT NULL DEFAULT 30 CHECK (daily_minutes BETWEEN 5 AND 1440),
    active_days_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(active_days_json)),
    preferences_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(preferences_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at TEXT
);

CREATE TABLE learning_goals (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    track_ref TEXT NOT NULL,
    goal_text TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    target_date TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'paused', 'completed')),
    calibration_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (calibration_status IN ('pending', 'in_progress', 'calibrated', 'skipped')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX idx_learning_goals_profile_status
    ON learning_goals(profile_id, status, priority DESC);

CREATE TABLE learning_plans (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    available_minutes INTEGER NOT NULL CHECK (available_minutes >= 0),
    generation_strategy TEXT NOT NULL,
    strategy_version TEXT NOT NULL,
    input_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(input_snapshot_json)),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('draft', 'active', 'completed', 'superseded')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (period_end >= period_start)
);

CREATE INDEX idx_learning_plans_profile_period
    ON learning_plans(profile_id, period_start, period_end);

CREATE TABLE plan_items (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL REFERENCES learning_plans(id) ON DELETE CASCADE,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    domain TEXT NOT NULL CHECK (domain IN ('english', 'fund', 'llm', 'common')),
    task_type TEXT NOT NULL,
    content_ref TEXT,
    content_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(content_snapshot_json)),
    scheduled_for TEXT NOT NULL,
    estimated_minutes INTEGER NOT NULL CHECK (estimated_minutes > 0),
    priority INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN ('planned', 'in_progress', 'completed', 'skipped', 'rescheduled')),
    completion_rule_json TEXT NOT NULL CHECK (json_valid(completion_rule_json)),
    completion_rule_version TEXT NOT NULL,
    skip_reason TEXT,
    skip_note TEXT,
    rescheduled_to_id TEXT REFERENCES plan_items(id) ON DELETE SET NULL,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (status <> 'skipped' OR skip_reason IS NOT NULL),
    CHECK (status <> 'completed' OR completed_at IS NOT NULL),
    CHECK (status <> 'rescheduled' OR rescheduled_to_id IS NOT NULL)
);

CREATE INDEX idx_plan_items_today
    ON plan_items(profile_id, scheduled_for, status, priority DESC);

CREATE INDEX idx_plan_items_plan_status
    ON plan_items(plan_id, status);

CREATE TABLE learning_sessions (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    plan_item_id TEXT REFERENCES plan_items(id) ON DELETE SET NULL,
    domain TEXT NOT NULL CHECK (domain IN ('english', 'fund', 'llm', 'common')),
    context_type TEXT NOT NULL,
    context_ref TEXT,
    context_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(context_json)),
    started_at TEXT NOT NULL,
    last_active_at TEXT NOT NULL,
    ended_at TEXT,
    active_seconds INTEGER NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
    end_reason TEXT,
    summary TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX idx_learning_sessions_profile_recent
    ON learning_sessions(profile_id, last_active_at DESC);

CREATE INDEX idx_learning_sessions_plan_item
    ON learning_sessions(plan_item_id, started_at DESC);

CREATE TABLE draft_checkpoints (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES learning_sessions(id) ON DELETE SET NULL,
    context_type TEXT NOT NULL,
    context_ref TEXT NOT NULL,
    payload_json TEXT NOT NULL CHECK (json_valid(payload_json)),
    content_version TEXT,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (profile_id, context_type, context_ref)
);

CREATE INDEX idx_draft_checkpoints_recent
    ON draft_checkpoints(profile_id, updated_at DESC);

CREATE TABLE attempts (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL REFERENCES learning_sessions(id) ON DELETE CASCADE,
    plan_item_id TEXT REFERENCES plan_items(id) ON DELETE SET NULL,
    exercise_ref TEXT NOT NULL,
    exercise_version TEXT NOT NULL,
    submission_key TEXT NOT NULL,
    answer_snapshot_json TEXT NOT NULL CHECK (json_valid(answer_snapshot_json)),
    result TEXT NOT NULL DEFAULT 'unscored'
        CHECK (result IN ('correct', 'partial', 'incorrect', 'unscored')),
    evaluation_status TEXT NOT NULL DEFAULT 'submitted'
        CHECK (evaluation_status IN ('submitted', 'evaluating', 'evaluated', 'evaluation_failed')),
    score REAL CHECK (score IS NULL OR (score >= 0.0 AND score <= 1.0)),
    hint_level INTEGER NOT NULL DEFAULT 0 CHECK (hint_level >= 0),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    feedback_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(feedback_json)),
    current_evaluation_version INTEGER NOT NULL DEFAULT 0 CHECK (current_evaluation_version >= 0),
    submitted_at TEXT NOT NULL,
    evaluated_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (profile_id, submission_key)
);

CREATE INDEX idx_attempts_exercise_recent
    ON attempts(profile_id, exercise_ref, submitted_at DESC);

CREATE INDEX idx_attempts_session
    ON attempts(session_id, submitted_at);

CREATE TABLE attempt_evaluations (
    id TEXT PRIMARY KEY,
    attempt_id TEXT NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
    version INTEGER NOT NULL CHECK (version >= 1),
    evaluator TEXT NOT NULL CHECK (evaluator IN ('local', 'rule', 'human', 'ai')),
    evaluator_name TEXT,
    evaluator_version TEXT,
    status TEXT NOT NULL CHECK (status IN ('completed', 'failed', 'cancelled', 'incomplete')),
    result TEXT CHECK (result IN ('correct', 'partial', 'incorrect', 'unscored')),
    score REAL CHECK (score IS NULL OR (score >= 0.0 AND score <= 1.0)),
    feedback_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(feedback_json)),
    error_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(error_json)),
    started_at TEXT NOT NULL,
    completed_at TEXT,
    is_current INTEGER NOT NULL DEFAULT 0 CHECK (is_current IN (0, 1)),
    UNIQUE (attempt_id, version)
);

CREATE UNIQUE INDEX idx_attempt_evaluations_one_current
    ON attempt_evaluations(attempt_id)
    WHERE is_current = 1;

CREATE TABLE learning_evidence (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL
        CHECK (source_type IN ('attempt', 'recording', 'case', 'lab_run', 'assessment', 'project', 'review')),
    source_id TEXT NOT NULL,
    evaluator TEXT NOT NULL CHECK (evaluator IN ('local', 'rule', 'human', 'ai')),
    quality TEXT NOT NULL CHECK (quality IN ('correct', 'partial', 'incorrect', 'unscored')),
    validity TEXT NOT NULL DEFAULT 'candidate'
        CHECK (validity IN ('candidate', 'pending', 'valid', 'invalid', 'superseded')),
    weight REAL NOT NULL DEFAULT 1.0 CHECK (weight >= 0.0 AND weight <= 1.0),
    evidence_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(evidence_json)),
    content_version TEXT,
    evaluation_version TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    superseded_by_id TEXT REFERENCES learning_evidence(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (validity <> 'superseded' OR superseded_by_id IS NOT NULL),
    UNIQUE (source_type, source_id, evaluator, evaluation_version)
);

CREATE INDEX idx_learning_evidence_profile_recent
    ON learning_evidence(profile_id, occurred_at DESC);

CREATE INDEX idx_learning_evidence_source
    ON learning_evidence(source_type, source_id);

CREATE TABLE evidence_concepts (
    evidence_id TEXT NOT NULL REFERENCES learning_evidence(id) ON DELETE CASCADE,
    concept_ref TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'primary'
        CHECK (role IN ('primary', 'supporting', 'prerequisite')),
    PRIMARY KEY (evidence_id, concept_ref)
);

CREATE INDEX idx_evidence_concepts_concept
    ON evidence_concepts(concept_ref, evidence_id);

CREATE TABLE plan_item_evidence (
    plan_item_id TEXT NOT NULL REFERENCES plan_items(id) ON DELETE CASCADE,
    evidence_id TEXT NOT NULL REFERENCES learning_evidence(id) ON DELETE CASCADE,
    completion_role TEXT NOT NULL DEFAULT 'supporting'
        CHECK (completion_role IN ('required', 'supporting')),
    PRIMARY KEY (plan_item_id, evidence_id)
);

CREATE TABLE concept_mastery (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    concept_ref TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'new'
        CHECK (state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    mastery_score REAL NOT NULL DEFAULT 0.0 CHECK (mastery_score >= 0.0 AND mastery_score <= 1.0),
    evidence_count INTEGER NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
    last_practiced_at TEXT,
    next_review_at TEXT,
    algorithm_name TEXT NOT NULL DEFAULT 'explainable_v1',
    algorithm_version TEXT NOT NULL DEFAULT '1',
    algorithm_data_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(algorithm_data_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (profile_id, concept_ref)
);

CREATE INDEX idx_concept_mastery_review_due
    ON concept_mastery(profile_id, next_review_at)
    WHERE next_review_at IS NOT NULL;

CREATE TABLE mastery_events (
    id TEXT PRIMARY KEY,
    mastery_id TEXT NOT NULL REFERENCES concept_mastery(id) ON DELETE CASCADE,
    evidence_id TEXT REFERENCES learning_evidence(id) ON DELETE SET NULL,
    previous_state TEXT NOT NULL
        CHECK (previous_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    new_state TEXT NOT NULL
        CHECK (new_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    previous_score REAL NOT NULL CHECK (previous_score >= 0.0 AND previous_score <= 1.0),
    new_score REAL NOT NULL CHECK (new_score >= 0.0 AND new_score <= 1.0),
    reason_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(reason_json)),
    algorithm_version TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX idx_mastery_events_mastery_recent
    ON mastery_events(mastery_id, created_at DESC);

CREATE TABLE review_cards (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    concept_ref TEXT NOT NULL,
    card_type TEXT NOT NULL,
    front_json TEXT NOT NULL CHECK (json_valid(front_json)),
    back_json TEXT NOT NULL CHECK (json_valid(back_json)),
    source_type TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    source_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(source_snapshot_json)),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'archived')),
    suspension_reason TEXT,
    next_review_at TEXT NOT NULL,
    interval_days REAL NOT NULL DEFAULT 0 CHECK (interval_days >= 0),
    difficulty REAL NOT NULL DEFAULT 0.5 CHECK (difficulty >= 0.0 AND difficulty <= 1.0),
    scheduling_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(scheduling_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    archived_at TEXT,
    CHECK (status <> 'suspended' OR suspension_reason IS NOT NULL)
);

CREATE INDEX idx_review_cards_due
    ON review_cards(profile_id, next_review_at)
    WHERE status = 'active';

CREATE TABLE review_logs (
    id TEXT PRIMARY KEY,
    card_id TEXT NOT NULL REFERENCES review_cards(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES learning_sessions(id) ON DELETE SET NULL,
    evidence_id TEXT REFERENCES learning_evidence(id) ON DELETE SET NULL,
    submission_key TEXT NOT NULL,
    rating TEXT NOT NULL CHECK (rating IN ('again', 'hard', 'good', 'easy')),
    correctness TEXT NOT NULL CHECK (correctness IN ('correct', 'partial', 'incorrect', 'unscored')),
    hint_level INTEGER NOT NULL DEFAULT 0 CHECK (hint_level >= 0),
    duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    previous_interval_days REAL NOT NULL CHECK (previous_interval_days >= 0),
    next_interval_days REAL NOT NULL CHECK (next_interval_days >= 0),
    reviewed_at TEXT NOT NULL,
    next_review_at TEXT NOT NULL,
    algorithm_version TEXT NOT NULL,
    UNIQUE (card_id, submission_key)
);

CREATE INDEX idx_review_logs_card_recent
    ON review_logs(card_id, reviewed_at DESC);

CREATE TABLE mistakes (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    attempt_id TEXT NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
    error_type TEXT NOT NULL,
    reason_note TEXT,
    remediation_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(remediation_json)),
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'observing', 'resolved')),
    observing_since TEXT,
    resolved_at TEXT,
    reopened_count INTEGER NOT NULL DEFAULT 0 CHECK (reopened_count >= 0),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (status <> 'observing' OR observing_since IS NOT NULL),
    CHECK (status <> 'resolved' OR resolved_at IS NOT NULL)
);

CREATE INDEX idx_mistakes_profile_status
    ON mistakes(profile_id, status, updated_at DESC);

CREATE TABLE mistake_concepts (
    mistake_id TEXT NOT NULL REFERENCES mistakes(id) ON DELETE CASCADE,
    concept_ref TEXT NOT NULL,
    PRIMARY KEY (mistake_id, concept_ref)
);

CREATE INDEX idx_mistake_concepts_concept
    ON mistake_concepts(concept_ref, mistake_id);

CREATE TABLE mistake_attempts (
    mistake_id TEXT NOT NULL REFERENCES mistakes(id) ON DELETE CASCADE,
    attempt_id TEXT NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
    relation TEXT NOT NULL CHECK (relation IN ('origin', 'redo', 'transfer')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (mistake_id, attempt_id)
);

CREATE TABLE notes (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    markdown TEXT NOT NULL DEFAULT '',
    tags_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(tags_json)),
    favorite INTEGER NOT NULL DEFAULT 0 CHECK (favorite IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at TEXT
);

CREATE INDEX idx_notes_profile_recent
    ON notes(profile_id, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE note_links (
    note_id TEXT NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    link_type TEXT NOT NULL,
    link_ref TEXT NOT NULL,
    link_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(link_snapshot_json)),
    PRIMARY KEY (note_id, link_type, link_ref)
);

CREATE TABLE materials (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    media_type TEXT NOT NULL,
    original_path TEXT,
    managed_path TEXT,
    sha256 TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    language TEXT,
    source TEXT NOT NULL,
    license_text TEXT,
    processing_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (processing_status IN ('pending', 'processing', 'ready', 'failed', 'cancelled')),
    processing_error_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(processing_error_json)),
    imported_at TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at TEXT,
    UNIQUE (profile_id, sha256)
);

CREATE INDEX idx_materials_profile_status
    ON materials(profile_id, processing_status, imported_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE material_segments (
    id TEXT PRIMARY KEY,
    material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    sequence_index INTEGER NOT NULL CHECK (sequence_index >= 0),
    page_number INTEGER,
    start_ms INTEGER,
    end_ms INTEGER,
    text_content TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (material_id, sequence_index),
    CHECK (page_number IS NULL OR page_number > 0),
    CHECK (start_ms IS NULL OR start_ms >= 0),
    CHECK (end_ms IS NULL OR (start_ms IS NOT NULL AND end_ms >= start_ms))
);

CREATE TABLE vocabulary_items (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    lemma TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'en',
    phonetic_us TEXT,
    phonetic_uk TEXT,
    meanings_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(meanings_json)),
    examples_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(examples_json)),
    source_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(source_refs_json)),
    recognition_state TEXT NOT NULL DEFAULT 'new',
    listening_state TEXT NOT NULL DEFAULT 'new',
    spelling_state TEXT NOT NULL DEFAULT 'new',
    production_state TEXT NOT NULL DEFAULT 'new',
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (profile_id, language, lemma),
    CHECK (recognition_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    CHECK (listening_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    CHECK (spelling_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed')),
    CHECK (production_state IN ('new', 'learning', 'reviewing', 'mastered', 'lapsed'))
);

CREATE TABLE audio_recordings (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES learning_sessions(id) ON DELETE SET NULL,
    file_path TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    duration_ms INTEGER NOT NULL CHECK (duration_ms >= 0),
    sample_rate INTEGER CHECK (sample_rate IS NULL OR sample_rate > 0),
    purpose TEXT NOT NULL,
    source_text TEXT,
    transcript TEXT,
    consent_scope_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(consent_scope_json)),
    processing_status TEXT NOT NULL DEFAULT 'saved'
        CHECK (processing_status IN ('saved', 'evaluating', 'assessed', 'failed')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at TEXT,
    UNIQUE (profile_id, sha256)
);

CREATE INDEX idx_audio_recordings_profile_recent
    ON audio_recordings(profile_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE speech_assessments (
    id TEXT PRIMARY KEY,
    recording_id TEXT NOT NULL REFERENCES audio_recordings(id) ON DELETE CASCADE,
    evaluator TEXT NOT NULL CHECK (evaluator IN ('local', 'rule', 'human', 'ai')),
    engine TEXT NOT NULL,
    engine_version TEXT NOT NULL,
    transcript_diff_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(transcript_diff_json)),
    pace_metrics_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(pace_metrics_json)),
    pause_metrics_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(pause_metrics_json)),
    pronunciation_findings_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(pronunciation_findings_json)),
    feedback TEXT,
    status TEXT NOT NULL CHECK (status IN ('completed', 'failed', 'cancelled', 'incomplete')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE fund_portfolios (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    base_currency TEXT NOT NULL,
    initial_cash NUMERIC NOT NULL CHECK (initial_cash >= 0),
    benchmark_ref TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    archived_at TEXT
);

CREATE TABLE fund_transactions (
    id TEXT PRIMARY KEY,
    portfolio_id TEXT NOT NULL REFERENCES fund_portfolios(id) ON DELETE CASCADE,
    instrument_ref TEXT NOT NULL,
    instrument_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(instrument_snapshot_json)),
    transaction_type TEXT NOT NULL
        CHECK (transaction_type IN ('subscribe', 'redeem', 'dividend', 'fee', 'deposit', 'withdraw')),
    trade_date TEXT NOT NULL,
    units NUMERIC,
    unit_price NUMERIC,
    gross_amount NUMERIC NOT NULL,
    fee_amount NUMERIC NOT NULL DEFAULT 0 CHECK (fee_amount >= 0),
    decision_log TEXT,
    data_source TEXT,
    data_as_of TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (units IS NULL OR units >= 0),
    CHECK (unit_price IS NULL OR unit_price >= 0)
);

CREATE INDEX idx_fund_transactions_portfolio_date
    ON fund_transactions(portfolio_id, trade_date, created_at);

CREATE TABLE fund_snapshots (
    id TEXT PRIMARY KEY,
    portfolio_id TEXT NOT NULL REFERENCES fund_portfolios(id) ON DELETE CASCADE,
    snapshot_date TEXT NOT NULL,
    portfolio_value NUMERIC NOT NULL,
    cash_value NUMERIC NOT NULL,
    return_value NUMERIC,
    drawdown_value NUMERIC,
    allocation_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(allocation_json)),
    data_source_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(data_source_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (portfolio_id, snapshot_date)
);

CREATE TABLE llm_projects (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    track_type TEXT NOT NULL CHECK (track_type IN ('application', 'algorithm', 'common')),
    goal TEXT NOT NULL,
    repository_path TEXT,
    repository_fingerprint TEXT,
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN ('planned', 'active', 'paused', 'completed', 'archived')),
    rubric_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(rubric_json)),
    started_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE project_milestones (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES llm_projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    acceptance_criteria_json TEXT NOT NULL CHECK (json_valid(acceptance_criteria_json)),
    due_date TEXT,
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN ('planned', 'in_progress', 'completed', 'skipped')),
    evidence_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(evidence_refs_json)),
    retrospective TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE lab_runs (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    submission_key TEXT NOT NULL,
    payload_sha256 TEXT NOT NULL,
    session_id TEXT REFERENCES learning_sessions(id) ON DELETE SET NULL,
    project_id TEXT REFERENCES llm_projects(id) ON DELETE SET NULL,
    lab_ref TEXT NOT NULL,
    lab_version TEXT NOT NULL,
    status TEXT NOT NULL
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    retry_of_run_id TEXT REFERENCES lab_runs(id) ON DELETE SET NULL,
    parameters_json TEXT NOT NULL CHECK (json_valid(parameters_json)),
    prediction_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(prediction_json)),
    result_json TEXT NOT NULL CHECK (json_valid(result_json)),
    secret_fields_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(secret_fields_json)),
    input_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(input_refs_json)),
    output_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(output_refs_json)),
    metrics_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metrics_json)),
    environment_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(environment_json)),
    log_path TEXT,
    conclusion TEXT,
    queued_at TEXT NOT NULL,
    started_at TEXT,
    finished_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (profile_id, submission_key)
);

CREATE INDEX idx_lab_runs_project_recent
    ON lab_runs(project_id, created_at DESC);

CREATE INDEX idx_lab_runs_profile_lab_recent
    ON lab_runs(profile_id, lab_ref, created_at DESC);

CREATE TABLE tutor_threads (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    context_type TEXT NOT NULL,
    context_ref TEXT NOT NULL,
    context_snapshot_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(context_snapshot_json)),
    title TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at TEXT
);

CREATE TABLE tutor_messages (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES tutor_threads(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    model_provider TEXT,
    model_name TEXT,
    processing_mode TEXT NOT NULL CHECK (processing_mode IN ('local', 'network', 'ai')),
    sent_remotely INTEGER NOT NULL DEFAULT 0 CHECK (sent_remotely IN (0, 1)),
    consent_scope_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(consent_scope_json)),
    context_summary_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(context_summary_json)),
    status TEXT NOT NULL DEFAULT 'completed'
        CHECK (status IN ('sending', 'streaming', 'completed', 'failed', 'cancelled', 'incomplete')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX idx_tutor_messages_thread
    ON tutor_messages(thread_id, created_at);

CREATE TABLE processing_jobs (
    id TEXT PRIMARY KEY,
    profile_id TEXT REFERENCES learner_profiles(id) ON DELETE CASCADE,
    job_type TEXT NOT NULL,
    context_type TEXT NOT NULL,
    context_ref TEXT NOT NULL,
    status TEXT NOT NULL
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    progress REAL CHECK (progress IS NULL OR (progress >= 0.0 AND progress <= 1.0)),
    input_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(input_json)),
    output_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(output_json)),
    error_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(error_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    started_at TEXT,
    finished_at TEXT,
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX idx_processing_jobs_status
    ON processing_jobs(status, created_at);

CREATE TABLE report_snapshots (
    id TEXT PRIMARY KEY,
    profile_id TEXT NOT NULL REFERENCES learner_profiles(id) ON DELETE CASCADE,
    domain TEXT NOT NULL CHECK (domain IN ('english', 'fund', 'llm', 'common')),
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    metric_version TEXT NOT NULL,
    evidence_cutoff_at TEXT NOT NULL,
    report_json TEXT NOT NULL CHECK (json_valid(report_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (period_end >= period_start)
);

CREATE INDEX idx_report_snapshots_profile_domain
    ON report_snapshots(profile_id, domain, created_at DESC);

INSERT INTO schema_migrations(version, name, checksum, app_version)
VALUES (1, 'learning_user_initial', 'DRAFT_REPLACE_WITH_SHA256', '0.1.0');

PRAGMA user_version = 1;

COMMIT;
